---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
  become: true

- name: Add site to nginx
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled
    group: "root"
    owner: "root"
    mode: "0644"
  become: true

- name: Create site folder
  ansible.builtin.file:
    state: directory
    path: /var/www/site
    group: "root"
    owner: "root"
    mode: "0644"
  become: true

- name: Copy html file
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/site/
    group: "root"
    owner: "root"
    mode: "0644"
  become: true

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
  become: true
