---
- name: Update cache & upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true

- name: Install challenge packages
  ansible.builtin.apt:
    pkg:
      - dnsutils
      - git
      - btop
  become: true